version: 2
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/elgolfin/adventofcode-2017
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            go test -cover ./...
      - run:
          name: "Get the results"
          command: |
            go install ./...
            day01 -input inputs/day01.txt
            day02 -input inputs/day02.txt