version: 2
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/elgolfin/adventofcode-2017
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            go test -cover ./...
      - run:
          name: "Get the results"
          command: |
            go install ./...
            day01 -input inputs/day01.txt
            day02 -input inputs/day02.txt
            day03 -input 312051
            day04 -input inputs/day04.txt
            day05 -input inputs/day05.txt
            day06 -input inputs/day06.txt
            day07 -input inputs/day07.txt
            day08 -input inputs/day08.txt
            day09 -input inputs/day09.txt
            day10 -input inputs/day10.txt
            day11 -input inputs/day11.txt
            day12 -input inputs/day12.txt
            day13 -input inputs/day13.txt
            day14 -input ffayrhll
            day15 -input 883,879
            day16 -input inputs/day16.txt
            day17 -input 304
            day18 -input inputs/day18.txt