version: 2
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: /go/src/github.com/elgolfin/adventofcode-2017
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            cd captcha
            go test -cover
      - run:
          name: "Get the results"
          command: |
            cd day01
            go build && ./day01