version: 2
jobs:
  build:
    docker:
      - image: golang:latest
    working_directory: ~/adventofcode-2017
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: |
            cd captcha
            go test
      - run:
          name: "Run the results"
          command: |
            cd day01
            go build && ./day01